### PR TITLE
chore: add script to auto update unicode-alias

### PR DESCRIPTION
**Pull request by ota-meshi**
This PR adds a script to automatically update unicode-alias.
I also added a GitHub Action to periodically check for updates.

### CODE REVIEW

**Review by RunDevelopment — APPROVED** [review]
Nice idea! Thank you @ota-meshi!

**Comment by fisker** [comment]
You can use action to create PR https://github.com/sindresorhus/get-east-asian-width/blob/61a40a00326ec6924a143d0fd0a01f3618714115/.github/workflows/update.yml#L18

**Comment by ota-meshi** [comment]
Very interesting! Can I see PRs created using that `peter-evans/create-pull-request`?
It looked like that repository didn't have it yet.
https://github.com/sindresorhus/get-east-asian-width/pulls?q=is%3Apr+is%3Aclosed

**Comment by fisker** [comment]
The data has not been updated yet.. See another repo  https://github.com/sindresorhus/globals/pull/245

**Comment by ota-meshi** [comment]
@fisker Thank you! I opened a PR to use it.

**Pull request merged**
